"""increase refresh token hash length

Revision ID: 5ee277868f19
Revises: 12bf0d607b08
Create Date: 2026-09-28 13:31:37.027406

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ee277868f19"
down_revision: str | Sequence[str] | None = "12bf0d607b08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_sessions",
        "refresh_token_hash",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_sessions",
        "refresh_token_hash",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
