"""redesion user session table

Revision ID: 653539cc89d2
Revises: 5ee277868f19
Create Date: 2026-10-01 12:57:03.039194

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "653539cc89d2"
down_revision: str | Sequence[str] | None = "5ee277868f19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions",
        sa.Column("refresh_expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.add_column(
        "user_sessions",
        sa.Column("session_expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_index(op.f("ix_user_sessions_token_family_id"), table_name="user_sessions")
    op.create_index(
        op.f("ix_user_sessions_refresh_expires_at"),
        "user_sessions",
        ["refresh_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_revoked_at"),
        "user_sessions",
        ["revoked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_session_expires_at"),
        "user_sessions",
        ["session_expires_at"],
        unique=False,
    )
    op.drop_column("user_sessions", "token_family_id")
    op.drop_column("user_sessions", "expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "user_sessions",
        sa.Column("token_family_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_index(
        op.f("ix_user_sessions_session_expires_at"), table_name="user_sessions"
    )
    op.drop_index(op.f("ix_user_sessions_revoked_at"), table_name="user_sessions")
    op.drop_index(
        op.f("ix_user_sessions_refresh_expires_at"), table_name="user_sessions"
    )
    op.create_index(
        op.f("ix_user_sessions_token_family_id"),
        "user_sessions",
        ["token_family_id"],
        unique=False,
    )
    op.drop_column("user_sessions", "session_expires_at")
    op.drop_column("user_sessions", "refresh_expires_at")
    # ### end Alembic commands ###
